@startuml
hide circle
skinparam linetype ortho

title __Diagram of org.broker.monitor.model__\n

entity node_entries {
    **id** : **int**
    --
    state : node_states
    info : node_infos
    contacts : email_contacts[]
    stats : node_stats[]
    errors : node_errors[]
    tags : node_tags[]
    comments : node_comments[]
    threshold_daily_imports: int
    threshold_error_rate : int
    error_rate_calendar_week : hstore
    --
    created_time : datetime
    modified_time : datetime
    modified_by : char(64)
}

enum node_states {
    Online
    Offline
    No Imports
    Deviating Imports
    High Error Rate
}
show node_states circle
hide node_states methods

entity node_infos {
    **id** : **int**
    --
    name : char(255)
    location : char(255)
    root_patient : char(128)
    format_patient : char(128)
    root_encounter : char(128)
    format_encounter : char(128)
    root_billing : char(128)
    format_billing : char(128)
    his : hospital_information_system
    interface_cda : clincal_data_interfaces
    member_since : datetime
    --
    created_time : datetime
    created_by : char(64)
    modified_time : datetime
    modified_by : char(64)
}

entity hospital_information_systems {
    **name** : **char(64)**
    --
    created_time : datetime
    created_by : char(64)
}

entity clincal_data_interfaces {
    **name** : **char(64)**
    --
    created_time : datetime
    created_by : char(64)
}

entity email_contacts {
    **email** : **char(255)**
    --
    name : char(255)
    contact_type : contact_types
    notify_import_threhshold : boolean
    notify_error_threshold : boolean
    notify_no_imports : boolean
    notify_no_connection : boolean
    --
    created_time : datetime
    created_by : char(64)
    modified_time : datetime
    modified_by : char(64)
}

enum contact_types {
    User
    IT Officer
    ER Manager
}
show contact_types circle
hide contact_types methods

entity node_stats {
    **id** : **sequence**
    --
    imported : int
    updated : int
    invalid : int
    failed : int
    last_start : datetime
    last_contact : datetime
    last_write : datetime
    last_reject : datetime
    daily_imports : int
    daily_updates : int
    daily_invalids : int
    daily_failed : int
    error_rate : float8
    --
    created_time : datetime
    modified_time : datetime
}

entity node_errors {
    **id** : **sequence**
    --
    timestamp : datetime
    repeats : int
    content : text
    --
    created_time : datetime
    modified_time : datetime
}

entity node_tags {
    **name** : **char(64)**
    --
    created_time : datetime
    created_by : char(64)
}

entity node_comments {
    **id** : **sequence**
    --
    content : string
    --
    created_time : datetime
    created_by : char(64)
    modified_time : datetime
    modified_by : char(64)
}

entity users {
    **username** : **char(64)**
    --
    password : char(255)
    roles : roles[]
    --
    created_time : datetime
    created_by : char(64)
    modified_time : datetime
    modified_by : char(64)
}

entity roles {
    **name** : **char(64)**
    --
    permissions : permissions[]
}

enum permissions {
    **ToDo**
}
show permissions circle
hide permissions methods


node_entries }o--|| node_states
node_entries ||--|| node_infos

node_infos }o--o| hospital_information_systems
node_infos }o--o| clincal_data_interfaces

node_entries }|--o{ email_contacts
email_contacts }o--|| contact_types

node_entries }o--o{ node_tags
node_entries ||-l-o{ node_comments
node_entries ||--|{ node_stats
node_entries ||-u-o{ node_errors

roles }o--|{ permissions
users }o--|{ roles


note bottom of email_contacts
    * Correspondents for nodes
    * "notify_" are the flags for email sending
end note

note top of node_entries
    * Additional node infos like versions/rscript/python/import-scripts
    are saved in a transient hashmap
    * Each end of week, corresponding daily error rates are averaged and
    saved in a map. Fixed length of 52. Entries from new year overwrite
    old year.
end note

note top of node_infos
    * Just the information from confluence
    * Do we even need pat/enc/bill format?
end note

note "Are they even necessary?" as N2
hospital_information_systems .. N2
clincal_data_interfaces .. N2

note top of node_stats
    * Node information from broker-server
    * Only one entry per node per day, but entries
      can be updated (if update cycle is set to 6h etc.)
    * Daily imports are computed from differences
      to previous day
    * error_rate is computed from
      (daily_invalids + daily_failed) / (daily_imports + daily_updates)
end note

note top of node_errors
    * Error information from broker-server
end note

@enduml
