@startuml
hide methods

title Diagram of csv_to_confluence.py

entity "<size:18>CONFLUENCE</size>" as confluence
entity confluence #aliceblue;line:blue;text:blue
hide confluence members
hide confluence circle

'###################################################################'

package "common.py" as common <<Package>> {
abstract class CSVHandler {
* initializes csv file in a path
* operations for reading a csv file as a dataframe
or writing a dataframe to a csv
}

class InfoCSVHandler {
* generates info csv name
* knows columns of info csv
}

class ErrorCSVHandler {
* generates error csv name
* knows columns of error csv
}

class TimestampHandler {
* gets current date information
* extracts information from given dates
* operations for time delta
}

abstract class "**ResourceLoader**" as ResourceLoader {
* loads resource files from
resource directory
}

class "**ConfluenceConnection**" as ConfluenceConnection {
* uses Atlassian Python API to execute CRUD
operations on confluence pages
}

class "**ConfluenceNodeMapper**" as ConfluenceNodeMapper {
* loads json file with confluence node mapping
as python dictionary
}
}

InfoCSVHandler -u-|> CSVHandler
ErrorCSVHandler -u-|> CSVHandler

ConfluenceConnection -d--> confluence

'###################################################################'

package "csv_to_confluence.py" as csv_to_confluence {
class TemplatePageElementCreator {
* creates html and confluence elements
for confluence page
}

class TemplatePageLoader {
* loads confluence page template from
resources directory
}

abstract class "**TemplatePageCSVContentWriter**" as TemplatePageCSVContentWriter {
* converts confluence page template to html soup
* provides abstract method to write information
from csv file into html soup
}

class TemplatePageCSVInfoWriter {
* writes csv import stats into confluence
page template
}

class TemplatePageCSVErrorWriter {
* writes csv error stats into confluence
page template
}

class TemplatePageStatusChecker {
* checks and sets import/connection status of
confluence page template
}

class TemplatePageMonitoringStartDateWriter {
* sets monitoring start date in confluence
page template on creation
}

class TemplatePageClinicInfoWriter {
* adds static information about clinic to
confluence page template on creation
}

abstract class "**TemplatePageContentWriter**" as TemplatePageContentWriter {
* converts confluence page template to html soup
* provides abstract method to write information
into html soup
}

class TemplatePageNodeResourceWriter {
* loads node resources from txt file and writes
information to confluence page template
}

class TemplatePageJiraTableWriter {
* adds jira table to confluence page template
}

class TemplatePageMigrator {
* checks confluence page for current template version
* migrates information set on creation of confluence
page to newer template
}

class ConfluenceClinicContactGrabber {
* grabs information about clinic correspondants
from confluence email page and writes them into
confluence page template
}

abstract class ConfluenceHandler {
* class to bundle common classes and variables
needed for Confluence
}

class ConfluencePageHandler {
* creates new pages for broker nodes on confluence
* updates content on existing broker node pages
* updates template of broker node pages to newer version
}

class "**FileBackupManager**" as FileBackupManager {
* uploads broker node files as attachement to
confluence page
}

class "**ConfluencePageHandlerManager**" as ConfluencePageHandlerManager {
* main class to run confluence page creation
* initializes and executes ConfluencePageHandler
* creates confluence page with summarization of
all connected nodes as parent page
}

class SummaryTableCreator {
* creates a confluence page with an
overview table of all connected nodes
}
}

TemplatePageLoader --|> ResourceLoader

TemplatePageContentWriter --> TemplatePageElementCreator

TemplatePageNodeResourceWriter --|> TemplatePageContentWriter

TemplatePageJiraTableWriter --|> TemplatePageContentWriter
TemplatePageJiraTableWriter --> ConfluenceNodeMapper

ConfluenceClinicContactGrabber --|> TemplatePageContentWriter

TemplatePageClinicInfoWriter --|> TemplatePageContentWriter
TemplatePageClinicInfoWriter --> ConfluenceNodeMapper

TemplatePageCSVContentWriter --|> TemplatePageContentWriter
TemplatePageCSVContentWriter --> TimestampHandler
TemplatePageCSVContentWriter --> CSVHandler

TemplatePageCSVInfoWriter --|> TemplatePageCSVContentWriter
TemplatePageCSVErrorWriter --|> TemplatePageCSVContentWriter

TemplatePageStatusChecker --|> TemplatePageCSVContentWriter
TemplatePageStatusChecker --> ConfluenceNodeMapper

TemplatePageMonitoringStartDateWriter --|> TemplatePageCSVContentWriter

TemplatePageMigrator --> TemplatePageLoader
TemplatePageMigrator --> TemplatePageElementCreator

ConfluenceHandler --> ConfluenceNodeMapper
ConfluenceHandler --> ConfluenceConnection

ConfluencePageHandler -d---|> ConfluenceHandler
ConfluencePageHandler -d---> TemplatePageLoader
ConfluencePageHandler -d---> TemplatePageMonitoringStartDateWriter
ConfluencePageHandler -d---> TemplatePageMigrator
ConfluencePageHandler -d---> TemplatePageClinicInfoWriter
ConfluencePageHandler -d---> ConfluenceClinicContactGrabber
ConfluencePageHandler -d---> TemplatePageCSVInfoWriter
ConfluencePageHandler -d---> TemplatePageCSVErrorWriter
ConfluencePageHandler -d---> TemplatePageNodeResourceWriter
ConfluencePageHandler -d---> TemplatePageJiraTableWriter
ConfluencePageHandler -d---> TemplatePageStatusChecker

FileBackupManager --|> ConfluenceHandler

SummaryTableCreator --> TemplatePageElementCreator

ConfluencePageHandlerManager --|> ConfluenceHandler
ConfluencePageHandlerManager --> ConfluencePageHandler
ConfluencePageHandlerManager --> SummaryTableCreator
ConfluencePageHandlerManager --> FileBackupManager

@enduml
