@startuml
hide methods

title Diagram of email_service.py

entity "<size:18>CONFLUENCE</size>" as confluence
entity confluence #aliceblue;line:blue;text:blue
hide confluence members
hide confluence circle

entity "<size:18>E-Mail Server</size>" as email
entity email #aliceblue;line:blue;text:blue
hide email members
hide email circle


'###################################################################'

package "common.py" as common <<Package>> {
abstract class "**ResourceLoader**" as ResourceLoader {
* loads resource files from
resource directory
}

class "**ConfluenceConnection**" as ConfluenceConnection {
* uses Atlassian Python API to execute CRUD
operations on confluence pages
}

class "**ConfluenceNodeMapper**" as ConfluenceNodeMapper {
* loads json file with confluence node mapping
as python dictionary
}

class TimestampHandler {
* gets current date information
* extracts information from given dates
* operations for time delta
}

abstract class "**MailServerConnection**" as MailServerConnection {
* connects to mail server with given configuration
from properties
}

class MailSender {
* sends given message object to given receiver
}

abstract class DataWriter {
* interface to store data in local files
}

class TextWriter {
* writes data to .txt files
}
}

TextWriter -d-|> DataWriter

MailServerConnection -d-> email
MailSender --|> MailServerConnection

ConfluenceConnection -d--> confluence

'###################################################################'

package "email_service.py" as email_service <<Package>> {

abstract class MailTemplateHandler {
* contains helper variables and abstract method to load
email template and fill its placeholder
}

class OfflineMailTemplateHandler {
* loads mail template for status "offline" and fills
template with information from given page template
}

class "**NoImportsMailTemplateHandler**" as NoImportsMailTemplateHandler {
* loads mail template for status "no imports" and fills
template with information from given page template
}

class "**OutdatedVersionMailTemplateHandler**" as OutdatedVersionMailTemplateHandler {
* loads mail template for status "outdated version" and fills
template with information from given page template
}

abstract class NotificationHandler {
* contains helper methods to check node for a specific
state and notify its correspondants
}

class OfflineNotificationHandler {
* checks node for the status "offline" and
notifies its correspondants
}

class NoImportsNotificationHandler {
* checks node for the status "no imports" and
notifies its correspondants
}

class "**OutdatedVersionNotificationHandler**" as OutdatedVersionNotificationHandler {
* checks node for the status "outdated version" and
notifies its correspondants
}

class ConfluencePageRecipientsExtractor {
* extracts contact information about clinic
correspondants from confluence email page
}

class "**ConsecutiveSentEmailsCounter**" as ConsecutiveSentEmailsCounter {
* keeps track of already informed nodes
about emergency status via json file
}

class "**SentMailsLogger**" as SentMailsLogger {
* keeps track of sent mails to nodes in a log file
}

class NodeEventNotifierManager {
* main class to check broker node status and
notify its correspondants
* gets all broker nodes and checks its states
}
}

MailTemplateHandler --|> ResourceLoader
OfflineMailTemplateHandler --|> MailTemplateHandler
NoImportsMailTemplateHandler --|> MailTemplateHandler
OutdatedVersionMailTemplateHandler --|> MailTemplateHandler

NotificationHandler --> MailTemplateHandler
NotificationHandler --> ConfluencePageRecipientsExtractor
NotificationHandler --> SentMailsLogger
NotificationHandler --> ConsecutiveSentEmailsCounter
NotificationHandler --> MailSender

OfflineNotificationHandler --|> NotificationHandler
NoImportsNotificationHandler --|> NotificationHandler
OutdatedVersionNotificationHandler --|> NotificationHandler

ConfluencePageRecipientsExtractor --> ConfluenceConnection

ConsecutiveSentEmailsCounter --> TimestampHandler
ConsecutiveSentEmailsCounter --> TextWriter
ConsecutiveSentEmailsCounter --> ConfluenceNodeMapper

SentMailsLogger --> TimestampHandler
SentMailsLogger --> TextWriter

NodeEventNotifierManager --> ConfluenceConnection
NodeEventNotifierManager --> ConfluenceNodeMapper
NodeEventNotifierManager --> OfflineNotificationHandler
NodeEventNotifierManager --> NoImportsNotificationHandler
NodeEventNotifierManager --> OutdatedVersionNotificationHandler

@enduml