@startuml
hide methods

title Diagram of node_to_csv.py

entity "<size:18>AKTIN Broker</size>" as broker
entity broker #aliceblue;line:blue;text:blue
hide broker members
hide broker circle

'###################################################################'

package "common.py" as common <<Package>> {
abstract class DataWriter {
* interface to store data in local files
}

abstract class CSVHandler {
* initializes csv file in a path
* operations for reading a csv file as a dataframe
or writing a dataframe to a csv
}

class InfoCSVHandler {
* generates info csv name
* knows columns of info csv
}

class ErrorCSVHandler {
* generates error csv name
* knows columns of error csv
}

class TextWriter {
* writes data to .txt files
}

class TimestampHandler {
* gets current date information
* extracts information from given dates
* operations for time delta
}

class "**BrokerNodeConnection**" as BrokerNodeConnection {
* uses REST endpoint of broker-server to get
information about connected broker nodes
}
}

CSVHandler -u-|> DataWriter
InfoCSVHandler -u-|> CSVHandler
ErrorCSVHandler -u-|> CSVHandler
TextWriter -u-|> DataWriter

BrokerNodeConnection -d----> broker

'###################################################################'

package "node_to_csv.py" as node_to_csv <<Package>> {
abstract class "**BrokerNodeRetriever**" as BrokerNodeRetriever {
* helper functions and variables to fetch broker node
information and save them in a file
* initializes directory for node to fetch information to
}

class NodeInfoRetriever {
* writes broker node last-contact, startup
and import stats into csv file
* computes daily imports and error rate from
differences to previous day
}

class NodeErrorRetriever {
* writes broker node errors into csv file
}

class NodeResourceRetriever {
* writes broker node resource information to text file
* keeps track of changes to node resources in a log file
}

class NodeRetrieverManager {
* initializes and executes retriever
}
}

BrokerNodeRetriever --> BrokerNodeConnection
BrokerNodeRetriever --> TimestampHandler
BrokerNodeRetriever --> DataWriter

NodeInfoRetriever --|> BrokerNodeRetriever

NodeErrorRetriever --|> BrokerNodeRetriever

NodeResourceRetriever --|> BrokerNodeRetriever

NodeRetrieverManager --> BrokerNodeConnection
NodeRetrieverManager --> NodeInfoRetriever
NodeRetrieverManager --> NodeErrorRetriever
NodeRetrieverManager --> NodeResourceRetriever

@enduml